version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5454:5432"
    networks:
      - dag_network
    env_file:
      - path: ./envs/db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
    volumes:
      - pg-data:/var/lib/postgresql/data

  keydb:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    networks:
      - dag_network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com # Change to your desired email
      PGADMIN_DEFAULT_PASSWORD: pass # Change to your desired password
    ports:
      - "9080:80" # Expose pgAdmin port
    depends_on:
      dagster:
        condition: service_started
    networks:
      - dag_network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  dagster:
    build:
      context: .
      dockerfile: Dockerfile
    image: dagster_all_in_one
    ports:
      - 3000:3000
      - 8080:8080
    env_file:
      - path: ./envs/dagster.env

    depends_on:
      postgres:
        condition: service_healthy
      keydb:
        condition: service_started

    networks:
      - dag_network
    volumes:
      # Make docker client accessible so we can launch containers using host docker
      - /run/user/1000/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage

networks:
  dag_network:
    driver: bridge
    name: dag_network

volumes:
  pg-data:
  pgadmin-data:
  dagster-data:
  keydb-data:
